### ISSUE TITLE
Support for regex expression in expected datasets

### ISSUE THREAD

**Issue by rmpestano** [arquillian/arquillian-extension-persistence#49]
example:

actual-users-regex.yml
```
useraccount:
  - id: 1
    firstname: John
    lastname: Smith
    username: doovde
    password: password
    openDate: 2014-01-01
```

expected-users-regex.yml
```
useraccount:
  - id: "regex:\\d+"
    firstname: regex:^Jo.* #John
    lastname: regex:.*ith$ #Smith
    username: regex:.oovd. #doovde
    password: password
    openDate: regex:^(?:[0-9]{2})?[0-9]{2}-[0-3]?[0-9]-[0-3]?[0-9]$
```

Do you think its useful?
